### ISSUE TITLE
deployment using rhsm will fail if using a bulky account

### ISSUE THREAD

**Issue by gprocunier** [shiftstack/dev-install#117]
This might not be exclusively a dev-install issue but I find when I use the employee sku which has eleventyfivehundred repos, the build will fail with this:

(Running it again seems to eventually succeed.  Perhaps this  task should have a succes/retry loop?)

```
TASK [redhat-subscription : Configure repository subscriptions] **************************************************************************************************************************************************************************************************************************************************************
task path: /home/greg/.ansible/roles/redhat-subscription/tasks/portal.yml:34
Using module file /home/greg/.ansible/roles/redhat-subscription/library/rhsm_repository_conf.py
Pipelining is enabled.
<10.10.0.100> ESTABLISH SSH CONNECTION FOR USER: stack
<10.10.0.100> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="stack"' -o ConnectTimeout=10 -o ControlPath=/home/greg/.ansible/cp/129b39cb34 10.10.0.100 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-evwttpxhvzosmiecwmcfpnpwyxfewghu ; /usr/libexec/platform-python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<10.10.0.100> (1, b'', b'Traceback (most recent call last):\n  File "<stdin>", line 102, in <module>\n  File "<stdin>", line 94, in _ansiballz_main\n  File "<stdin>", line 40, in invoke_module\n  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "/tmp/ansible_rhsm_repository_conf_payload_66e14_5h/ansible_rhsm_repository_conf_payload.zip/ansible/modules/rhsm_repository_conf.py", line 294, in <module>\n  File "/tmp/ansible_rhsm_repository_conf_payload_66e14_5h/ansible_rhsm_repository_conf_payload.zip/ansible/modules/rhsm_repository_conf.py", line 290, in main\n  File "/tmp/ansible_rhsm_repository_conf_payload_66e14_5h/ansible_rhsm_repository_conf_payload.zip/ansible/modules/rhsm_repository_conf.py", line 195, in repository_modify\n  File "/tmp/ansible_rhsm_repository_conf_payload_66e14_5h/ansible_rhsm_repository_conf_payload.zip/ansible/modules/rhsm_repository_conf.py", line 188, in get_repository_list\nUnboundLocalError: local variable \'repo\' referenced before assignment\n')
<10.10.0.100> Failed to connect to the host via ssh: Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_rhsm_repository_conf_payload_66e14_5h/ansible_rhsm_repository_conf_payload.zip/ansible/modules/rhsm_repository_conf.py", line 294, in <module>
  File "/tmp/ansible_rhsm_repository_conf_payload_66e14_5h/ansible_rhsm_repository_conf_payload.zip/ansible/modules/rhsm_repository_conf.py", line 290, in main
  File "/tmp/ansible_rhsm_repository_conf_payload_66e14_5h/ansible_rhsm_repository_conf_payload.zip/ansible/modules/rhsm_repository_conf.py", line 195, in repository_modify
  File "/tmp/ansible_rhsm_repository_conf_payload_66e14_5h/ansible_rhsm_repository_conf_payload.zip/ansible/modules/rhsm_repository_conf.py", line 188, in get_repository_list
UnboundLocalError: local variable 'repo' referenced before assignment
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_rhsm_repository_conf_payload_66e14_5h/ansible_rhsm_repository_conf_payload.zip/ansible/modules/rhsm_repository_conf.py", line 294, in <module>
  File "/tmp/ansible_rhsm_repository_conf_payload_66e14_5h/ansible_rhsm_repository_conf_payload.zip/ansible/modules/rhsm_repository_conf.py", line 290, in main
  File "/tmp/ansible_rhsm_repository_conf_payload_66e14_5h/ansible_rhsm_repository_conf_payload.zip/ansible/modules/rhsm_repository_conf.py", line 195, in repository_modify
  File "/tmp/ansible_rhsm_repository_conf_payload_66e14_5h/ansible_rhsm_repository_conf_payload.zip/ansible/modules/rhsm_repository_conf.py", line 188, in get_repository_list
UnboundLocalError: local variable 'repo' referenced before assignment
fatal: [standalone]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_rhsm_repository_conf_payload_66e14_5h/ansible_rhsm_repository_conf_payload.zip/ansible/modules/rhsm_repository_conf.py\", line 294, in <module>\n  File \"/tmp/ansible_rhsm_repository_conf_payload_66e14_5h/ansible_rhsm_repository_conf_payload.zip/ansible/modules/rhsm_repository_conf.py\", line 290, in main\n  File \"/tmp/ansible_rhsm_repository_conf_payload_66e14_5h/ansible_rhsm_repository_conf_payload.zip/ansible/modules/rhsm_repository_conf.py\", line 195, in repository_modify\n  File \"/tmp/ansible_rhsm_repository_conf_payload_66e14_5h/ansible_rhsm_repository_conf_payload.zip/ansible/modules/rhsm_repository_conf.py\", line 188, in get_repository_list\nUnboundLocalError: local variable 'repo' referenced before assignment\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************************************************************
standalone                 : ok=6    changed=2    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0   

make: *** [Makefile:61: prepare_host] Error 2
```

**Comment by gprocunier** [comment]
This is the step the above error failed on:

![image](https://user-images.githubusercontent.com/49077358/123823378-22477080-d8cb-11eb-8b99-d9aee9844847.png)

**Comment by EmilienM** [comment]
This is a bug to file against RHSM or the Ansible role for RHSM.
