### ISSUE TITLE
stack-update does fails looking for underloud log file

### ISSUE THREAD

**Issue by adduarte** [shiftstack/dev-install#136]
After deploying a cluster, if update is attempted by copying "tripleo_deploy.sh" to "tripleo_update.sh" and adding "--force-stack-update" the process fails. 
For example. 
the command being executed ends up being: 

sudo openstack tripleo deploy --templates /usr/share/openstack-tripleo-heat-templates --standalone --yes --output-dir /home/stack --stack standalone --standalone-role Standalone --timeout 90 -e /usr/share/openstack-tripleo-heat-templates/environments/standalone/standalone-tripleo.yaml -e /home/stack/containers-prepare-parameters.yaml -e /home/stack/standalone_parameters.yaml -e /usr/share/openstack-tripleo-heat-templates/environments/services/octavia.yaml -r /usr/share/openstack-tripleo-heat-templates/roles/Standalone.yaml --deployment-user stack --local-ip 10.8.1.135 --control-virtual-ip 10.8.1.135 --keep-running --force-stack-update

But this fails with: 
[EXPERIMENTAL] The tripleo deploy interface is an experimental interface. It may change in the next release.
The heat stack standalone action is UPDATE
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 461, in fire_timers
    timer()
  File "/usr/lib/python3.6/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/usr/lib/python3.6/site-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/eventlet/wsgi.py", line 818, in process_request
    proto.__init__(conn_state, self)
  File "/usr/lib/python3.6/site-packages/eventlet/wsgi.py", line 357, in __init__
    self.handle()
  File "/usr/lib/python3.6/site-packages/eventlet/wsgi.py", line 390, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/site-packages/eventlet/wsgi.py", line 466, in handle_one_request
    self.handle_one_response()
  File "/usr/lib/python3.6/site-packages/eventlet/wsgi.py", line 649, in handle_one_response
    'wall_seconds': finish - start,
  File "/usr/lib64/python3.6/logging/__init__.py", line 1636, in info
    self.log(INFO, msg, *args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1674, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1374, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib64/python3.6/logging/handlers.py", line 482, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1071, in emit
    self.stream = self._open()
  File "/usr/lib64/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/var/log/heat-launcher/undercloud_deploy-0qlmw33u/heat.log'

**Comment by adduarte** [comment]
not an issue
