### ISSUE TITLE
ansible lint error in our CI

### ISSUE THREAD

**Issue by EmilienM** [shiftstack/dev-install#179]
```
 + ansible-lint -v --force-color -x 602 playbooks/certs.yaml playbooks/destroy.yaml playbooks/install_stack.yaml playbooks/local_os_client.yaml playbooks/local_requirements.yaml playbooks/network.yaml playbooks/post_install.yaml playbooks/prepare_host.yaml playbooks/prepare_stack.yaml playbooks/prepare_stack_testconfig.yaml
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 5, in <module>
    from ansiblelint.__main__ import main
  File "/usr/local/lib/python3.8/site-packages/ansiblelint/__main__.py", line 37, in <module>
    from ansiblelint.generate_docs import rules_as_rich, rules_as_rst
  File "/usr/local/lib/python3.8/site-packages/ansiblelint/generate_docs.py", line 6, in <module>
    from rich.console import render_group
ImportError: cannot import name 'render_group' from 'rich.console' (/usr/local/lib/python3.8/site-packages/rich/console.py)
```

https://github.com/shiftstack/dev-install/runs/4938208378?check_suite_focus=true

**Comment by EmilienM** [comment]
Already reported here: https://github.com/ansible/ansible-lint-action/issues/59
